# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import poq_pb2 as poq__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in poq_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PoQStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUniverse = channel.unary_unary(
                '/poq.PoQ/GetUniverse',
                request_serializer=poq__pb2.UniverseRequest.SerializeToString,
                response_deserializer=poq__pb2.UniverseResponse.FromString,
                _registered_method=True)
        self.StartSession = channel.unary_unary(
                '/poq.PoQ/StartSession',
                request_serializer=poq__pb2.SessionStartRequest.SerializeToString,
                response_deserializer=poq__pb2.SessionStartResponse.FromString,
                _registered_method=True)
        self.StreamSession = channel.stream_stream(
                '/poq.PoQ/StreamSession',
                request_serializer=poq__pb2.SessionMessageRequest.SerializeToString,
                response_deserializer=poq__pb2.SessionMessageResponse.FromString,
                _registered_method=True)


class PoQServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUniverse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSession(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PoQServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUniverse': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUniverse,
                    request_deserializer=poq__pb2.UniverseRequest.FromString,
                    response_serializer=poq__pb2.UniverseResponse.SerializeToString,
            ),
            'StartSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSession,
                    request_deserializer=poq__pb2.SessionStartRequest.FromString,
                    response_serializer=poq__pb2.SessionStartResponse.SerializeToString,
            ),
            'StreamSession': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamSession,
                    request_deserializer=poq__pb2.SessionMessageRequest.FromString,
                    response_serializer=poq__pb2.SessionMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'poq.PoQ', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('poq.PoQ', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PoQ(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUniverse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/poq.PoQ/GetUniverse',
            poq__pb2.UniverseRequest.SerializeToString,
            poq__pb2.UniverseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/poq.PoQ/StartSession',
            poq__pb2.SessionStartRequest.SerializeToString,
            poq__pb2.SessionStartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSession(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/poq.PoQ/StreamSession',
            poq__pb2.SessionMessageRequest.SerializeToString,
            poq__pb2.SessionMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
