// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.29.0
// source: poq.proto

package poq

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionMessageType int32

const (
	SessionMessageType_UNKNOWN               SessionMessageType = 0
	SessionMessageType_START                 SessionMessageType = 1
	SessionMessageType_STOP                  SessionMessageType = 2
	SessionMessageType_PING                  SessionMessageType = 3
	SessionMessageType_PONG                  SessionMessageType = 4
	SessionMessageType_LOGIN                 SessionMessageType = 5
	SessionMessageType_LOGOUT                SessionMessageType = 6
	SessionMessageType_CHARACTER_STATIC_INFO SessionMessageType = 7
	SessionMessageType_CHARACTER_LIVE_INFO   SessionMessageType = 8
	SessionMessageType_SYSTEM_STATIC_INFO    SessionMessageType = 9
	SessionMessageType_SYSTEM_LIVE_INFO      SessionMessageType = 10
	SessionMessageType_JOIN_SYSTEM           SessionMessageType = 11
	SessionMessageType_LEAVE_SYSTEM          SessionMessageType = 12
	SessionMessageType_BLEUGH                SessionMessageType = 99
)

// Enum value maps for SessionMessageType.
var (
	SessionMessageType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "START",
		2:  "STOP",
		3:  "PING",
		4:  "PONG",
		5:  "LOGIN",
		6:  "LOGOUT",
		7:  "CHARACTER_STATIC_INFO",
		8:  "CHARACTER_LIVE_INFO",
		9:  "SYSTEM_STATIC_INFO",
		10: "SYSTEM_LIVE_INFO",
		11: "JOIN_SYSTEM",
		12: "LEAVE_SYSTEM",
		99: "BLEUGH",
	}
	SessionMessageType_value = map[string]int32{
		"UNKNOWN":               0,
		"START":                 1,
		"STOP":                  2,
		"PING":                  3,
		"PONG":                  4,
		"LOGIN":                 5,
		"LOGOUT":                6,
		"CHARACTER_STATIC_INFO": 7,
		"CHARACTER_LIVE_INFO":   8,
		"SYSTEM_STATIC_INFO":    9,
		"SYSTEM_LIVE_INFO":      10,
		"JOIN_SYSTEM":           11,
		"LEAVE_SYSTEM":          12,
		"BLEUGH":                99,
	}
)

func (x SessionMessageType) Enum() *SessionMessageType {
	p := new(SessionMessageType)
	*p = x
	return p
}

func (x SessionMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_poq_proto_enumTypes[0].Descriptor()
}

func (SessionMessageType) Type() protoreflect.EnumType {
	return &file_poq_proto_enumTypes[0]
}

func (x SessionMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionMessageType.Descriptor instead.
func (SessionMessageType) EnumDescriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{0}
}

type ServiceStart_ServiceType int32

const (
	ServiceStart_UNKNOWN   ServiceStart_ServiceType = 0
	ServiceStart_GATEWAY   ServiceStart_ServiceType = 1
	ServiceStart_SESSION   ServiceStart_ServiceType = 2
	ServiceStart_CHARACTER ServiceStart_ServiceType = 3
	ServiceStart_SYSTEM    ServiceStart_ServiceType = 4
)

// Enum value maps for ServiceStart_ServiceType.
var (
	ServiceStart_ServiceType_name = map[int32]string{
		0: "UNKNOWN",
		1: "GATEWAY",
		2: "SESSION",
		3: "CHARACTER",
		4: "SYSTEM",
	}
	ServiceStart_ServiceType_value = map[string]int32{
		"UNKNOWN":   0,
		"GATEWAY":   1,
		"SESSION":   2,
		"CHARACTER": 3,
		"SYSTEM":    4,
	}
)

func (x ServiceStart_ServiceType) Enum() *ServiceStart_ServiceType {
	p := new(ServiceStart_ServiceType)
	*p = x
	return p
}

func (x ServiceStart_ServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceStart_ServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_poq_proto_enumTypes[1].Descriptor()
}

func (ServiceStart_ServiceType) Type() protoreflect.EnumType {
	return &file_poq_proto_enumTypes[1]
}

func (x ServiceStart_ServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceStart_ServiceType.Descriptor instead.
func (ServiceStart_ServiceType) EnumDescriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{1, 0}
}

type TopicMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestTopic   string `protobuf:"bytes,1,opt,name=request_topic,json=requestTopic,proto3" json:"request_topic,omitempty"`
	PublishTopic   string `protobuf:"bytes,2,opt,name=publish_topic,json=publishTopic,proto3" json:"publish_topic,omitempty"`
	SubscribeTopic string `protobuf:"bytes,3,opt,name=subscribe_topic,json=subscribeTopic,proto3" json:"subscribe_topic,omitempty"`
}

func (x *TopicMessage) Reset() {
	*x = TopicMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopicMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicMessage) ProtoMessage() {}

func (x *TopicMessage) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicMessage.ProtoReflect.Descriptor instead.
func (*TopicMessage) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{0}
}

func (x *TopicMessage) GetRequestTopic() string {
	if x != nil {
		return x.RequestTopic
	}
	return ""
}

func (x *TopicMessage) GetPublishTopic() string {
	if x != nil {
		return x.PublishTopic
	}
	return ""
}

func (x *TopicMessage) GetSubscribeTopic() string {
	if x != nil {
		return x.SubscribeTopic
	}
	return ""
}

type ServiceStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      ServiceStart_ServiceType `protobuf:"varint,1,opt,name=type,proto3,enum=poq.ServiceStart_ServiceType" json:"type,omitempty"`
	Timestamp *timestamppb.Timestamp   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *ServiceStart) Reset() {
	*x = ServiceStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStart) ProtoMessage() {}

func (x *ServiceStart) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStart.ProtoReflect.Descriptor instead.
func (*ServiceStart) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceStart) GetType() ServiceStart_ServiceType {
	if x != nil {
		return x.Type
	}
	return ServiceStart_UNKNOWN
}

func (x *ServiceStart) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type CharacterStaticInfoMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterId int32  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CharacterStaticInfoMessage) Reset() {
	*x = CharacterStaticInfoMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterStaticInfoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterStaticInfoMessage) ProtoMessage() {}

func (x *CharacterStaticInfoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterStaticInfoMessage.ProtoReflect.Descriptor instead.
func (*CharacterStaticInfoMessage) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{2}
}

func (x *CharacterStaticInfoMessage) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *CharacterStaticInfoMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CharacterStaticInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterId int32 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
}

func (x *CharacterStaticInfoRequest) Reset() {
	*x = CharacterStaticInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterStaticInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterStaticInfoRequest) ProtoMessage() {}

func (x *CharacterStaticInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterStaticInfoRequest.ProtoReflect.Descriptor instead.
func (*CharacterStaticInfoRequest) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{3}
}

func (x *CharacterStaticInfoRequest) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type CharacterStaticInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok                  bool                        `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	CharacterStaticInfo *CharacterStaticInfoMessage `protobuf:"bytes,2,opt,name=character_static_info,json=characterStaticInfo,proto3" json:"character_static_info,omitempty"`
}

func (x *CharacterStaticInfoResponse) Reset() {
	*x = CharacterStaticInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterStaticInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterStaticInfoResponse) ProtoMessage() {}

func (x *CharacterStaticInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterStaticInfoResponse.ProtoReflect.Descriptor instead.
func (*CharacterStaticInfoResponse) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{4}
}

func (x *CharacterStaticInfoResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CharacterStaticInfoResponse) GetCharacterStaticInfo() *CharacterStaticInfoMessage {
	if x != nil {
		return x.CharacterStaticInfo
	}
	return nil
}

type CharacterLiveInfoMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterId int32 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	SystemId    int32 `protobuf:"varint,2,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	Active      bool  `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
}

func (x *CharacterLiveInfoMessage) Reset() {
	*x = CharacterLiveInfoMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterLiveInfoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterLiveInfoMessage) ProtoMessage() {}

func (x *CharacterLiveInfoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterLiveInfoMessage.ProtoReflect.Descriptor instead.
func (*CharacterLiveInfoMessage) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{5}
}

func (x *CharacterLiveInfoMessage) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *CharacterLiveInfoMessage) GetSystemId() int32 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

func (x *CharacterLiveInfoMessage) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type CharacterLiveInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterId int32 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
}

func (x *CharacterLiveInfoRequest) Reset() {
	*x = CharacterLiveInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterLiveInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterLiveInfoRequest) ProtoMessage() {}

func (x *CharacterLiveInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterLiveInfoRequest.ProtoReflect.Descriptor instead.
func (*CharacterLiveInfoRequest) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{6}
}

func (x *CharacterLiveInfoRequest) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type CharacterLiveInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok                bool                      `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	CharacterId       int32                     `protobuf:"varint,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	CharacterLiveInfo *CharacterLiveInfoMessage `protobuf:"bytes,3,opt,name=character_live_info,json=characterLiveInfo,proto3" json:"character_live_info,omitempty"`
	RequestTopic      string                    `protobuf:"bytes,4,opt,name=request_topic,json=requestTopic,proto3" json:"request_topic,omitempty"`
	PublishTopic      string                    `protobuf:"bytes,5,opt,name=publish_topic,json=publishTopic,proto3" json:"publish_topic,omitempty"`
	SubscribeTopic    string                    `protobuf:"bytes,6,opt,name=subscribe_topic,json=subscribeTopic,proto3" json:"subscribe_topic,omitempty"`
}

func (x *CharacterLiveInfoResponse) Reset() {
	*x = CharacterLiveInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterLiveInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterLiveInfoResponse) ProtoMessage() {}

func (x *CharacterLiveInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterLiveInfoResponse.ProtoReflect.Descriptor instead.
func (*CharacterLiveInfoResponse) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{7}
}

func (x *CharacterLiveInfoResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CharacterLiveInfoResponse) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *CharacterLiveInfoResponse) GetCharacterLiveInfo() *CharacterLiveInfoMessage {
	if x != nil {
		return x.CharacterLiveInfo
	}
	return nil
}

func (x *CharacterLiveInfoResponse) GetRequestTopic() string {
	if x != nil {
		return x.RequestTopic
	}
	return ""
}

func (x *CharacterLiveInfoResponse) GetPublishTopic() string {
	if x != nil {
		return x.PublishTopic
	}
	return ""
}

func (x *CharacterLiveInfoResponse) GetSubscribeTopic() string {
	if x != nil {
		return x.SubscribeTopic
	}
	return ""
}

type CharacterLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterId int32 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
}

func (x *CharacterLoginRequest) Reset() {
	*x = CharacterLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterLoginRequest) ProtoMessage() {}

func (x *CharacterLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterLoginRequest.ProtoReflect.Descriptor instead.
func (*CharacterLoginRequest) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{8}
}

func (x *CharacterLoginRequest) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type CharacterLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok                bool                      `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	CharacterId       int32                     `protobuf:"varint,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	CharacterLiveInfo *CharacterLiveInfoMessage `protobuf:"bytes,3,opt,name=character_live_info,json=characterLiveInfo,proto3" json:"character_live_info,omitempty"`
}

func (x *CharacterLoginResponse) Reset() {
	*x = CharacterLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterLoginResponse) ProtoMessage() {}

func (x *CharacterLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterLoginResponse.ProtoReflect.Descriptor instead.
func (*CharacterLoginResponse) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{9}
}

func (x *CharacterLoginResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CharacterLoginResponse) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *CharacterLoginResponse) GetCharacterLiveInfo() *CharacterLiveInfoMessage {
	if x != nil {
		return x.CharacterLiveInfo
	}
	return nil
}

type CharacterLogoutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterId int32 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
}

func (x *CharacterLogoutRequest) Reset() {
	*x = CharacterLogoutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterLogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterLogoutRequest) ProtoMessage() {}

func (x *CharacterLogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterLogoutRequest.ProtoReflect.Descriptor instead.
func (*CharacterLogoutRequest) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{10}
}

func (x *CharacterLogoutRequest) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type CharacterLogoutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok          bool  `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	CharacterId int32 `protobuf:"varint,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
}

func (x *CharacterLogoutResponse) Reset() {
	*x = CharacterLogoutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterLogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterLogoutResponse) ProtoMessage() {}

func (x *CharacterLogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterLogoutResponse.ProtoReflect.Descriptor instead.
func (*CharacterLogoutResponse) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{11}
}

func (x *CharacterLogoutResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CharacterLogoutResponse) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type CharacterTopicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterId int32 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
}

func (x *CharacterTopicRequest) Reset() {
	*x = CharacterTopicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterTopicRequest) ProtoMessage() {}

func (x *CharacterTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterTopicRequest.ProtoReflect.Descriptor instead.
func (*CharacterTopicRequest) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{12}
}

func (x *CharacterTopicRequest) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type CharacterTopicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok              bool          `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	CharacterId     int32         `protobuf:"varint,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	CharacterTopics *TopicMessage `protobuf:"bytes,3,opt,name=character_topics,json=characterTopics,proto3" json:"character_topics,omitempty"`
}

func (x *CharacterTopicResponse) Reset() {
	*x = CharacterTopicResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterTopicResponse) ProtoMessage() {}

func (x *CharacterTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterTopicResponse.ProtoReflect.Descriptor instead.
func (*CharacterTopicResponse) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{13}
}

func (x *CharacterTopicResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CharacterTopicResponse) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *CharacterTopicResponse) GetCharacterTopics() *TopicMessage {
	if x != nil {
		return x.CharacterTopics
	}
	return nil
}

type SystemStaticInfoMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SystemId   int32   `protobuf:"varint,1,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	Name       string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Neighbours []int32 `protobuf:"varint,3,rep,packed,name=neighbours,proto3" json:"neighbours,omitempty"`
}

func (x *SystemStaticInfoMessage) Reset() {
	*x = SystemStaticInfoMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemStaticInfoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStaticInfoMessage) ProtoMessage() {}

func (x *SystemStaticInfoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStaticInfoMessage.ProtoReflect.Descriptor instead.
func (*SystemStaticInfoMessage) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{14}
}

func (x *SystemStaticInfoMessage) GetSystemId() int32 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

func (x *SystemStaticInfoMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SystemStaticInfoMessage) GetNeighbours() []int32 {
	if x != nil {
		return x.Neighbours
	}
	return nil
}

type Universe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Universe) Reset() {
	*x = Universe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Universe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Universe) ProtoMessage() {}

func (x *Universe) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Universe.ProtoReflect.Descriptor instead.
func (*Universe) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{15}
}

type UniverseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UniverseRequest) Reset() {
	*x = UniverseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniverseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniverseRequest) ProtoMessage() {}

func (x *UniverseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniverseRequest.ProtoReflect.Descriptor instead.
func (*UniverseRequest) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{16}
}

type UniverseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok      bool                       `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Systems []*SystemStaticInfoMessage `protobuf:"bytes,2,rep,name=systems,proto3" json:"systems,omitempty"`
}

func (x *UniverseResponse) Reset() {
	*x = UniverseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniverseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniverseResponse) ProtoMessage() {}

func (x *UniverseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniverseResponse.ProtoReflect.Descriptor instead.
func (*UniverseResponse) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{17}
}

func (x *UniverseResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *UniverseResponse) GetSystems() []*SystemStaticInfoMessage {
	if x != nil {
		return x.Systems
	}
	return nil
}

type SystemStaticInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SystemId int32 `protobuf:"varint,1,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
}

func (x *SystemStaticInfoRequest) Reset() {
	*x = SystemStaticInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemStaticInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStaticInfoRequest) ProtoMessage() {}

func (x *SystemStaticInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStaticInfoRequest.ProtoReflect.Descriptor instead.
func (*SystemStaticInfoRequest) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{18}
}

func (x *SystemStaticInfoRequest) GetSystemId() int32 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

type SystemStaticInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok               bool                     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	SystemId         int32                    `protobuf:"varint,2,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	SystemStaticInfo *SystemStaticInfoMessage `protobuf:"bytes,3,opt,name=system_static_info,json=systemStaticInfo,proto3" json:"system_static_info,omitempty"`
}

func (x *SystemStaticInfoResponse) Reset() {
	*x = SystemStaticInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemStaticInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStaticInfoResponse) ProtoMessage() {}

func (x *SystemStaticInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStaticInfoResponse.ProtoReflect.Descriptor instead.
func (*SystemStaticInfoResponse) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{19}
}

func (x *SystemStaticInfoResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SystemStaticInfoResponse) GetSystemId() int32 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

func (x *SystemStaticInfoResponse) GetSystemStaticInfo() *SystemStaticInfoMessage {
	if x != nil {
		return x.SystemStaticInfo
	}
	return nil
}

type SystemLiveInfoMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SystemId    int32   `protobuf:"varint,1,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	CharacterId []int32 `protobuf:"varint,2,rep,packed,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
}

func (x *SystemLiveInfoMessage) Reset() {
	*x = SystemLiveInfoMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemLiveInfoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemLiveInfoMessage) ProtoMessage() {}

func (x *SystemLiveInfoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemLiveInfoMessage.ProtoReflect.Descriptor instead.
func (*SystemLiveInfoMessage) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{20}
}

func (x *SystemLiveInfoMessage) GetSystemId() int32 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

func (x *SystemLiveInfoMessage) GetCharacterId() []int32 {
	if x != nil {
		return x.CharacterId
	}
	return nil
}

type SystemLiveInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SystemId int32 `protobuf:"varint,1,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
}

func (x *SystemLiveInfoRequest) Reset() {
	*x = SystemLiveInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemLiveInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemLiveInfoRequest) ProtoMessage() {}

func (x *SystemLiveInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemLiveInfoRequest.ProtoReflect.Descriptor instead.
func (*SystemLiveInfoRequest) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{21}
}

func (x *SystemLiveInfoRequest) GetSystemId() int32 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

type SystemLiveInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok             bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	SystemId       int32                  `protobuf:"varint,2,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	SystemLiveInfo *SystemLiveInfoMessage `protobuf:"bytes,3,opt,name=system_live_info,json=systemLiveInfo,proto3" json:"system_live_info,omitempty"`
}

func (x *SystemLiveInfoResponse) Reset() {
	*x = SystemLiveInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemLiveInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemLiveInfoResponse) ProtoMessage() {}

func (x *SystemLiveInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemLiveInfoResponse.ProtoReflect.Descriptor instead.
func (*SystemLiveInfoResponse) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{22}
}

func (x *SystemLiveInfoResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SystemLiveInfoResponse) GetSystemId() int32 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

func (x *SystemLiveInfoResponse) GetSystemLiveInfo() *SystemLiveInfoMessage {
	if x != nil {
		return x.SystemLiveInfo
	}
	return nil
}

type SystemSetLiveCharacterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterId int32 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	SystemId    int32 `protobuf:"varint,2,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	Present     bool  `protobuf:"varint,3,opt,name=present,proto3" json:"present,omitempty"`
}

func (x *SystemSetLiveCharacterRequest) Reset() {
	*x = SystemSetLiveCharacterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemSetLiveCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemSetLiveCharacterRequest) ProtoMessage() {}

func (x *SystemSetLiveCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemSetLiveCharacterRequest.ProtoReflect.Descriptor instead.
func (*SystemSetLiveCharacterRequest) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{23}
}

func (x *SystemSetLiveCharacterRequest) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *SystemSetLiveCharacterRequest) GetSystemId() int32 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

func (x *SystemSetLiveCharacterRequest) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

type SystemSetLiveCharacterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok          bool  `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	CharacterId int32 `protobuf:"varint,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	SystemId    int32 `protobuf:"varint,3,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
}

func (x *SystemSetLiveCharacterResponse) Reset() {
	*x = SystemSetLiveCharacterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemSetLiveCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemSetLiveCharacterResponse) ProtoMessage() {}

func (x *SystemSetLiveCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemSetLiveCharacterResponse.ProtoReflect.Descriptor instead.
func (*SystemSetLiveCharacterResponse) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{24}
}

func (x *SystemSetLiveCharacterResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SystemSetLiveCharacterResponse) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *SystemSetLiveCharacterResponse) GetSystemId() int32 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

type SystemTopicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SystemId int32 `protobuf:"varint,1,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
}

func (x *SystemTopicRequest) Reset() {
	*x = SystemTopicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemTopicRequest) ProtoMessage() {}

func (x *SystemTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemTopicRequest.ProtoReflect.Descriptor instead.
func (*SystemTopicRequest) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{25}
}

func (x *SystemTopicRequest) GetSystemId() int32 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

type SystemTopicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok           bool          `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	SystemId     int32         `protobuf:"varint,2,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	SystemTopics *TopicMessage `protobuf:"bytes,3,opt,name=system_topics,json=systemTopics,proto3" json:"system_topics,omitempty"`
}

func (x *SystemTopicResponse) Reset() {
	*x = SystemTopicResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemTopicResponse) ProtoMessage() {}

func (x *SystemTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemTopicResponse.ProtoReflect.Descriptor instead.
func (*SystemTopicResponse) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{26}
}

func (x *SystemTopicResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SystemTopicResponse) GetSystemId() int32 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

func (x *SystemTopicResponse) GetSystemTopics() *TopicMessage {
	if x != nil {
		return x.SystemTopics
	}
	return nil
}

type SessionStartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *SessionStartRequest) Reset() {
	*x = SessionStartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStartRequest) ProtoMessage() {}

func (x *SessionStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStartRequest.ProtoReflect.Descriptor instead.
func (*SessionStartRequest) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{27}
}

func (x *SessionStartRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type SessionStartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok            bool          `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	CharacterId   int32         `protobuf:"varint,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	SessionId     string        `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionTopics *TopicMessage `protobuf:"bytes,4,opt,name=session_topics,json=sessionTopics,proto3" json:"session_topics,omitempty"`
}

func (x *SessionStartResponse) Reset() {
	*x = SessionStartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStartResponse) ProtoMessage() {}

func (x *SessionStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStartResponse.ProtoReflect.Descriptor instead.
func (*SessionStartResponse) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{28}
}

func (x *SessionStartResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SessionStartResponse) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *SessionStartResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionStartResponse) GetSessionTopics() *TopicMessage {
	if x != nil {
		return x.SessionTopics
	}
	return nil
}

type SessionStopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *SessionStopRequest) Reset() {
	*x = SessionStopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStopRequest) ProtoMessage() {}

func (x *SessionStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStopRequest.ProtoReflect.Descriptor instead.
func (*SessionStopRequest) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{29}
}

func (x *SessionStopRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionStopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok        bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *SessionStopResponse) Reset() {
	*x = SessionStopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStopResponse) ProtoMessage() {}

func (x *SessionStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStopResponse.ProtoReflect.Descriptor instead.
func (*SessionStopResponse) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{30}
}

func (x *SessionStopResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SessionStopResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionPing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *SessionPing) Reset() {
	*x = SessionPing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionPing) ProtoMessage() {}

func (x *SessionPing) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionPing.ProtoReflect.Descriptor instead.
func (*SessionPing) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{31}
}

func (x *SessionPing) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionPong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *SessionPong) Reset() {
	*x = SessionPong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionPong) ProtoMessage() {}

func (x *SessionPong) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionPong.ProtoReflect.Descriptor instead.
func (*SessionPong) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{32}
}

func (x *SessionPong) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        SessionMessageType `protobuf:"varint,1,opt,name=type,proto3,enum=poq.SessionMessageType" json:"type,omitempty"`
	CharacterId int32              `protobuf:"varint,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	SystemId    int32              `protobuf:"varint,3,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
}

func (x *SessionMessageRequest) Reset() {
	*x = SessionMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMessageRequest) ProtoMessage() {}

func (x *SessionMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMessageRequest.ProtoReflect.Descriptor instead.
func (*SessionMessageRequest) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{33}
}

func (x *SessionMessageRequest) GetType() SessionMessageType {
	if x != nil {
		return x.Type
	}
	return SessionMessageType_UNKNOWN
}

func (x *SessionMessageRequest) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *SessionMessageRequest) GetSystemId() int32 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

type SessionMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type                SessionMessageType          `protobuf:"varint,1,opt,name=type,proto3,enum=poq.SessionMessageType" json:"type,omitempty"`
	Ok                  bool                        `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Pingpong            int32                       `protobuf:"varint,4,opt,name=pingpong,proto3" json:"pingpong,omitempty"`
	CharacterStaticInfo *CharacterStaticInfoMessage `protobuf:"bytes,7,opt,name=character_static_info,json=characterStaticInfo,proto3" json:"character_static_info,omitempty"`
	CharacterLiveInfo   *CharacterLiveInfoMessage   `protobuf:"bytes,8,opt,name=character_live_info,json=characterLiveInfo,proto3" json:"character_live_info,omitempty"`
	SystemStaticInfo    *SystemStaticInfoMessage    `protobuf:"bytes,9,opt,name=system_static_info,json=systemStaticInfo,proto3" json:"system_static_info,omitempty"`
	SystemLiveInfo      *SystemLiveInfoMessage      `protobuf:"bytes,10,opt,name=system_live_info,json=systemLiveInfo,proto3" json:"system_live_info,omitempty"`
}

func (x *SessionMessageResponse) Reset() {
	*x = SessionMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poq_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMessageResponse) ProtoMessage() {}

func (x *SessionMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poq_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMessageResponse.ProtoReflect.Descriptor instead.
func (*SessionMessageResponse) Descriptor() ([]byte, []int) {
	return file_poq_proto_rawDescGZIP(), []int{34}
}

func (x *SessionMessageResponse) GetType() SessionMessageType {
	if x != nil {
		return x.Type
	}
	return SessionMessageType_UNKNOWN
}

func (x *SessionMessageResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SessionMessageResponse) GetPingpong() int32 {
	if x != nil {
		return x.Pingpong
	}
	return 0
}

func (x *SessionMessageResponse) GetCharacterStaticInfo() *CharacterStaticInfoMessage {
	if x != nil {
		return x.CharacterStaticInfo
	}
	return nil
}

func (x *SessionMessageResponse) GetCharacterLiveInfo() *CharacterLiveInfoMessage {
	if x != nil {
		return x.CharacterLiveInfo
	}
	return nil
}

func (x *SessionMessageResponse) GetSystemStaticInfo() *SystemStaticInfoMessage {
	if x != nil {
		return x.SystemStaticInfo
	}
	return nil
}

func (x *SessionMessageResponse) GetSystemLiveInfo() *SystemLiveInfoMessage {
	if x != nil {
		return x.SystemLiveInfo
	}
	return nil
}

var File_poq_proto protoreflect.FileDescriptor

var file_poq_proto_rawDesc = []byte{
	0x0a, 0x09, 0x70, 0x6f, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x70, 0x6f, 0x71,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x81, 0x01, 0x0a, 0x0c, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x5f, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x27, 0x0a, 0x0f,
	0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x5f, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x54, 0x6f, 0x70, 0x69, 0x63, 0x22, 0xcc, 0x01, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x31, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x70, 0x6f, 0x71, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x22, 0x4f, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x47, 0x41, 0x54, 0x45, 0x57, 0x41, 0x59, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07,
	0x53, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x48, 0x41,
	0x52, 0x41, 0x43, 0x54, 0x45, 0x52, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x59, 0x53, 0x54,
	0x45, 0x4d, 0x10, 0x04, 0x22, 0x53, 0x0a, 0x1a, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3f, 0x0a, 0x1a, 0x43, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x82, 0x01, 0x0a, 0x1b, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x53, 0x0a, 0x15, 0x63, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x6f, 0x71, 0x2e,
	0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x49,
	0x6e, 0x66, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x13, 0x63, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0x72, 0x0a, 0x18, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x76, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x22, 0x3d, 0x0a, 0x18, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x4c, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x90, 0x02, 0x0a, 0x19, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x4c, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b,
	0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x4d, 0x0a, 0x13, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x5f, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x70, 0x6f, 0x71, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x4c, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x11, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x76, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x5f, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x27, 0x0a, 0x0f,
	0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x5f, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x54, 0x6f, 0x70, 0x69, 0x63, 0x22, 0x3a, 0x0a, 0x15, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x9a, 0x01, 0x0a, 0x16, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x21, 0x0a, 0x0c,
	0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x4d, 0x0a, 0x13, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x76,
	0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70,
	0x6f, 0x71, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x76, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x11, 0x63, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x3b,
	0x0a, 0x16, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x6f, 0x75,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x17, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x15, 0x43, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x89, 0x01, 0x0a, 0x16, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b,
	0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x10, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x5f, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x70, 0x6f, 0x71, 0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x0f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x54, 0x6f, 0x70, 0x69, 0x63,
	0x73, 0x22, 0x6a, 0x0a, 0x17, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x69,
	0x63, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x75, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x05, 0x52, 0x0a, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x75, 0x72, 0x73, 0x22, 0x0a, 0x0a,
	0x08, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x55, 0x6e, 0x69,
	0x76, 0x65, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5a, 0x0a, 0x10,
	0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b,
	0x12, 0x36, 0x0a, 0x07, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x6f, 0x71, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x07, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x36, 0x0a, 0x17, 0x53, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x64,
	0x22, 0x93, 0x01, 0x0a, 0x18, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x69,
	0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x4a, 0x0a, 0x12, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x6f, 0x71, 0x2e, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x10, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74,
	0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x57, 0x0a, 0x15, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x4c, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x05, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x34, 0x0a, 0x15, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x49, 0x64, 0x22, 0x8b, 0x01, 0x0a, 0x16, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x4c, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x44, 0x0a,
	0x10, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x6f, 0x71, 0x2e, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x0e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x76, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x22, 0x79, 0x0a, 0x1d, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x65, 0x74,
	0x4c, 0x69, 0x76, 0x65, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x22, 0x70,
	0x0a, 0x1e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x65, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b,
	0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x64,
	0x22, 0x31, 0x0a, 0x12, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x49, 0x64, 0x22, 0x7a, 0x0a, 0x13, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x54, 0x6f, 0x70,
	0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x36, 0x0a, 0x0d, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x5f, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x70, 0x6f, 0x71, 0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x0c, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x22,
	0x31, 0x0a, 0x13, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0xa2, 0x01, 0x0a, 0x14, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x21, 0x0a, 0x0c, 0x63,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x38, 0x0a,
	0x0e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x6f, 0x71, 0x2e, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0d, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x22, 0x33, 0x0a, 0x12, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x13,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x02, 0x6f, 0x6b, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x22, 0x2c, 0x0a, 0x0b, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x69, 0x6e,
	0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x22, 0x2c, 0x0a, 0x0b, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x6e, 0x67, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x84,
	0x01, 0x0a, 0x15, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x6f, 0x71, 0x2e, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x49, 0x64, 0x22, 0xa7, 0x03, 0x0a, 0x16, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2b, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17,
	0x2e, 0x70, 0x6f, 0x71, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x69, 0x6e, 0x67, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x70, 0x69, 0x6e, 0x67, 0x70, 0x6f, 0x6e, 0x67, 0x12, 0x53, 0x0a, 0x15, 0x63, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x6f, 0x71, 0x2e, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x49, 0x6e,
	0x66, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x13, 0x63, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x4d,
	0x0a, 0x13, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x76, 0x65,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x6f,
	0x71, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x76, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x11, 0x63, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x4a, 0x0a,
	0x12, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x6f, 0x71, 0x2e,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x10, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x44, 0x0a, 0x10, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x5f, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x6f, 0x71, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x4c, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x0e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2a,
	0xf2, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x01, 0x12, 0x08,
	0x0a, 0x04, 0x53, 0x54, 0x4f, 0x50, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x49, 0x4e, 0x47,
	0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x4f, 0x4e, 0x47, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05,
	0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x4f, 0x47, 0x4f, 0x55,
	0x54, 0x10, 0x06, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x48, 0x41, 0x52, 0x41, 0x43, 0x54, 0x45, 0x52,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x49, 0x43, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x07, 0x12, 0x17,
	0x0a, 0x13, 0x43, 0x48, 0x41, 0x52, 0x41, 0x43, 0x54, 0x45, 0x52, 0x5f, 0x4c, 0x49, 0x56, 0x45,
	0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x08, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x59, 0x53, 0x54, 0x45,
	0x4d, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x49, 0x43, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x09, 0x12,
	0x14, 0x0a, 0x10, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x5f, 0x4c, 0x49, 0x56, 0x45, 0x5f, 0x49,
	0x4e, 0x46, 0x4f, 0x10, 0x0a, 0x12, 0x0f, 0x0a, 0x0b, 0x4a, 0x4f, 0x49, 0x4e, 0x5f, 0x53, 0x59,
	0x53, 0x54, 0x45, 0x4d, 0x10, 0x0b, 0x12, 0x10, 0x0a, 0x0c, 0x4c, 0x45, 0x41, 0x56, 0x45, 0x5f,
	0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x10, 0x0c, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x4c, 0x45, 0x55,
	0x47, 0x48, 0x10, 0x63, 0x32, 0xd4, 0x01, 0x0a, 0x03, 0x50, 0x6f, 0x51, 0x12, 0x3a, 0x0a, 0x0b,
	0x47, 0x65, 0x74, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x65, 0x12, 0x14, 0x2e, 0x70, 0x6f,
	0x71, 0x2e, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x70, 0x6f, 0x71, 0x2e, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x2e, 0x70, 0x6f, 0x71, 0x2e, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x6f, 0x71, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a,
	0x0d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a,
	0x2e, 0x70, 0x6f, 0x71, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x6f, 0x71,
	0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x06, 0x5a, 0x04, 0x2f,
	0x70, 0x6f, 0x71, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_poq_proto_rawDescOnce sync.Once
	file_poq_proto_rawDescData = file_poq_proto_rawDesc
)

func file_poq_proto_rawDescGZIP() []byte {
	file_poq_proto_rawDescOnce.Do(func() {
		file_poq_proto_rawDescData = protoimpl.X.CompressGZIP(file_poq_proto_rawDescData)
	})
	return file_poq_proto_rawDescData
}

var file_poq_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_poq_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_poq_proto_goTypes = []interface{}{
	(SessionMessageType)(0),                // 0: poq.SessionMessageType
	(ServiceStart_ServiceType)(0),          // 1: poq.ServiceStart.ServiceType
	(*TopicMessage)(nil),                   // 2: poq.TopicMessage
	(*ServiceStart)(nil),                   // 3: poq.ServiceStart
	(*CharacterStaticInfoMessage)(nil),     // 4: poq.CharacterStaticInfoMessage
	(*CharacterStaticInfoRequest)(nil),     // 5: poq.CharacterStaticInfoRequest
	(*CharacterStaticInfoResponse)(nil),    // 6: poq.CharacterStaticInfoResponse
	(*CharacterLiveInfoMessage)(nil),       // 7: poq.CharacterLiveInfoMessage
	(*CharacterLiveInfoRequest)(nil),       // 8: poq.CharacterLiveInfoRequest
	(*CharacterLiveInfoResponse)(nil),      // 9: poq.CharacterLiveInfoResponse
	(*CharacterLoginRequest)(nil),          // 10: poq.CharacterLoginRequest
	(*CharacterLoginResponse)(nil),         // 11: poq.CharacterLoginResponse
	(*CharacterLogoutRequest)(nil),         // 12: poq.CharacterLogoutRequest
	(*CharacterLogoutResponse)(nil),        // 13: poq.CharacterLogoutResponse
	(*CharacterTopicRequest)(nil),          // 14: poq.CharacterTopicRequest
	(*CharacterTopicResponse)(nil),         // 15: poq.CharacterTopicResponse
	(*SystemStaticInfoMessage)(nil),        // 16: poq.SystemStaticInfoMessage
	(*Universe)(nil),                       // 17: poq.Universe
	(*UniverseRequest)(nil),                // 18: poq.UniverseRequest
	(*UniverseResponse)(nil),               // 19: poq.UniverseResponse
	(*SystemStaticInfoRequest)(nil),        // 20: poq.SystemStaticInfoRequest
	(*SystemStaticInfoResponse)(nil),       // 21: poq.SystemStaticInfoResponse
	(*SystemLiveInfoMessage)(nil),          // 22: poq.SystemLiveInfoMessage
	(*SystemLiveInfoRequest)(nil),          // 23: poq.SystemLiveInfoRequest
	(*SystemLiveInfoResponse)(nil),         // 24: poq.SystemLiveInfoResponse
	(*SystemSetLiveCharacterRequest)(nil),  // 25: poq.SystemSetLiveCharacterRequest
	(*SystemSetLiveCharacterResponse)(nil), // 26: poq.SystemSetLiveCharacterResponse
	(*SystemTopicRequest)(nil),             // 27: poq.SystemTopicRequest
	(*SystemTopicResponse)(nil),            // 28: poq.SystemTopicResponse
	(*SessionStartRequest)(nil),            // 29: poq.SessionStartRequest
	(*SessionStartResponse)(nil),           // 30: poq.SessionStartResponse
	(*SessionStopRequest)(nil),             // 31: poq.SessionStopRequest
	(*SessionStopResponse)(nil),            // 32: poq.SessionStopResponse
	(*SessionPing)(nil),                    // 33: poq.SessionPing
	(*SessionPong)(nil),                    // 34: poq.SessionPong
	(*SessionMessageRequest)(nil),          // 35: poq.SessionMessageRequest
	(*SessionMessageResponse)(nil),         // 36: poq.SessionMessageResponse
	(*timestamppb.Timestamp)(nil),          // 37: google.protobuf.Timestamp
}
var file_poq_proto_depIdxs = []int32{
	1,  // 0: poq.ServiceStart.type:type_name -> poq.ServiceStart.ServiceType
	37, // 1: poq.ServiceStart.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 2: poq.CharacterStaticInfoResponse.character_static_info:type_name -> poq.CharacterStaticInfoMessage
	7,  // 3: poq.CharacterLiveInfoResponse.character_live_info:type_name -> poq.CharacterLiveInfoMessage
	7,  // 4: poq.CharacterLoginResponse.character_live_info:type_name -> poq.CharacterLiveInfoMessage
	2,  // 5: poq.CharacterTopicResponse.character_topics:type_name -> poq.TopicMessage
	16, // 6: poq.UniverseResponse.systems:type_name -> poq.SystemStaticInfoMessage
	16, // 7: poq.SystemStaticInfoResponse.system_static_info:type_name -> poq.SystemStaticInfoMessage
	22, // 8: poq.SystemLiveInfoResponse.system_live_info:type_name -> poq.SystemLiveInfoMessage
	2,  // 9: poq.SystemTopicResponse.system_topics:type_name -> poq.TopicMessage
	2,  // 10: poq.SessionStartResponse.session_topics:type_name -> poq.TopicMessage
	0,  // 11: poq.SessionMessageRequest.type:type_name -> poq.SessionMessageType
	0,  // 12: poq.SessionMessageResponse.type:type_name -> poq.SessionMessageType
	4,  // 13: poq.SessionMessageResponse.character_static_info:type_name -> poq.CharacterStaticInfoMessage
	7,  // 14: poq.SessionMessageResponse.character_live_info:type_name -> poq.CharacterLiveInfoMessage
	16, // 15: poq.SessionMessageResponse.system_static_info:type_name -> poq.SystemStaticInfoMessage
	22, // 16: poq.SessionMessageResponse.system_live_info:type_name -> poq.SystemLiveInfoMessage
	18, // 17: poq.PoQ.GetUniverse:input_type -> poq.UniverseRequest
	29, // 18: poq.PoQ.StartSession:input_type -> poq.SessionStartRequest
	35, // 19: poq.PoQ.StreamSession:input_type -> poq.SessionMessageRequest
	19, // 20: poq.PoQ.GetUniverse:output_type -> poq.UniverseResponse
	30, // 21: poq.PoQ.StartSession:output_type -> poq.SessionStartResponse
	36, // 22: poq.PoQ.StreamSession:output_type -> poq.SessionMessageResponse
	20, // [20:23] is the sub-list for method output_type
	17, // [17:20] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_poq_proto_init() }
func file_poq_proto_init() {
	if File_poq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_poq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopicMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CharacterStaticInfoMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CharacterStaticInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CharacterStaticInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CharacterLiveInfoMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CharacterLiveInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CharacterLiveInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CharacterLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CharacterLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CharacterLogoutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CharacterLogoutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CharacterTopicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CharacterTopicResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemStaticInfoMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Universe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniverseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniverseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemStaticInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemStaticInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemLiveInfoMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemLiveInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemLiveInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemSetLiveCharacterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemSetLiveCharacterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemTopicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemTopicResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionStartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionStartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionStopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionStopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionPing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionPong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poq_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_poq_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_poq_proto_goTypes,
		DependencyIndexes: file_poq_proto_depIdxs,
		EnumInfos:         file_poq_proto_enumTypes,
		MessageInfos:      file_poq_proto_msgTypes,
	}.Build()
	File_poq_proto = out.File
	file_poq_proto_rawDesc = nil
	file_poq_proto_goTypes = nil
	file_poq_proto_depIdxs = nil
}
